$(document).ready(function(){
    $('#angus').click(function(){
        $('#product-right-container').load('templates/secciones/angus.php');
    });
    $('#beefmaster').click(function(){
        $('#product-right-container').load('templates/secciones/beefmaster.php');
    });
    $('#belmontRed').click(function(){
        $('#product-right-container').load('templates/secciones/belmontRed.php');
    });
    $('#tudanca').click(function(){
        $('#product-right-container').load('templates/secciones/tudanca.php');
    });
    $('#leche').click(function(){
        $('#product-right-container').load('templates/secciones/leche.php');
    });
    $('#queso').click(function(){
        $('#product-right-container').load('templates/secciones/queso.php');
    });
    $('#crema').click(function(){
        $('#product-right-container').load('templates/secciones/crema.php');
    });
    $('#mantequilla').click(function(){
        $('#product-right-container').load('templates/secciones/mantequilla.php');
    });
    $('#cortes').click(function(){
        $('#product-right-container').load('templates/secciones/cortes.php');
    });
});


