$(document).ready(function(){
    $('#home').click(function(){
        $('#content').load('templates/carrusel.php');
    });
    $('#about').click(function(){
        $('#content').load('templates/acercade.php');
    });
    $('#products').click(function(){
        $('#content').load('templates/productos.php');
    });
    $('#contact').click(function(){
        $('#content').load('templates/contacto.php');
    });
});